project_name: repobook

before:
  hooks:
    - go test ./...

builds:
  - id: repobook
    main: ./cmd/repobook
    binary: repobook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
