name: Bug report
description: Report a problem with repobook
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: How can we reproduce it?
      placeholder: |
        1. Run ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or attach screenshots if helpful.
      render: text
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Go version, browser, etc.
      placeholder: |
        OS:
        Go:
        Browser:
        repobook commit:
    validations:
      required: true
